package cn.henry.domain.cargo;

import cn.henry.domain.BaseEntity;

public class Huohao extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_huohao.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_huohao.huohao_name
     *
     * @mbg.generated
     */
    private String huohaoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_huohao.factory_name
     *
     * @mbg.generated
     */
    private String factoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_huohao.factory_id
     *
     * @mbg.generated
     */
    private String factoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_huohao.ctype
     *
     * @mbg.generated
     */
    private String ctype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_huohao.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_huohao.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_huohao.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_huohao.id
     *
     * @return the value of co_huohao.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_huohao.id
     *
     * @param id the value for co_huohao.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_huohao.huohao_name
     *
     * @return the value of co_huohao.huohao_name
     *
     * @mbg.generated
     */
    public String getHuohaoName() {
        return huohaoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_huohao.huohao_name
     *
     * @param huohaoName the value for co_huohao.huohao_name
     *
     * @mbg.generated
     */
    public void setHuohaoName(String huohaoName) {
        this.huohaoName = huohaoName == null ? null : huohaoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_huohao.factory_name
     *
     * @return the value of co_huohao.factory_name
     *
     * @mbg.generated
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_huohao.factory_name
     *
     * @param factoryName the value for co_huohao.factory_name
     *
     * @mbg.generated
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName == null ? null : factoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_huohao.factory_id
     *
     * @return the value of co_huohao.factory_id
     *
     * @mbg.generated
     */
    public String getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_huohao.factory_id
     *
     * @param factoryId the value for co_huohao.factory_id
     *
     * @mbg.generated
     */
    public void setFactoryId(String factoryId) {
        this.factoryId = factoryId == null ? null : factoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_huohao.ctype
     *
     * @return the value of co_huohao.ctype
     *
     * @mbg.generated
     */
    public String getCtype() {
        return ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_huohao.ctype
     *
     * @param ctype the value for co_huohao.ctype
     *
     * @mbg.generated
     */
    public void setCtype(String ctype) {
        this.ctype = ctype == null ? null : ctype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_huohao.state
     *
     * @return the value of co_huohao.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_huohao.state
     *
     * @param state the value for co_huohao.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_huohao.company_id
     *
     * @return the value of co_huohao.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_huohao.company_id
     *
     * @param companyId the value for co_huohao.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_huohao.company_name
     *
     * @return the value of co_huohao.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_huohao.company_name
     *
     * @param companyName the value for co_huohao.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }
}