package cn.henry.dao.cargo;

import cn.henry.domain.cargo.Huohao;
import cn.henry.domain.cargo.HuohaoExample;

import java.util.List;

public interface HuohaoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_huohao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_huohao
     *
     * @mbg.generated
     */
    int insert(Huohao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_huohao
     *
     * @mbg.generated
     */
    int insertSelective(Huohao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_huohao
     *
     * @mbg.generated
     */
    List<Huohao> selectByExample(HuohaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_huohao
     *
     * @mbg.generated
     */
    Huohao selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_huohao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Huohao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_huohao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Huohao record);
}